# Generated by Django 3.1.2 on 2021-01-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_desc',
            field=models.CharField(default='default', max_length=600),
            preserve_default=False,
        ),
    ]
