# Generated by Django 3.1.2 on 2021-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_news_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='news_app.Category'),
        ),
    ]
